// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoieGP8rd4Sl3wHzk5J4R_dAr1HcLyO10',
    appId: '1:940511856789:web:365dc3e446451c72e9739c',
    messagingSenderId: '940511856789',
    projectId: 'online-gallery-app-8109a',
    authDomain: 'online-gallery-app-8109a.firebaseapp.com',
    storageBucket: 'online-gallery-app-8109a.appspot.com',
    measurementId: 'G-47SD4E9KKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXB-8B9UbyA9c9FJ-bBUDCHagCl17hBI',
    appId: '1:940511856789:android:c9ee2d16be4cd3dce9739c',
    messagingSenderId: '940511856789',
    projectId: 'online-gallery-app-8109a',
    storageBucket: 'online-gallery-app-8109a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9or9bhJYHGj0f_MLLxPFx4DPYPbJvhQ',
    appId: '1:940511856789:ios:155323cc0c8bf9f0e9739c',
    messagingSenderId: '940511856789',
    projectId: 'online-gallery-app-8109a',
    storageBucket: 'online-gallery-app-8109a.appspot.com',
    iosBundleId: 'com.example.onlinegalleryapp.onlineGalleryApp',
  );
}
